# Generated by Django 6.0.1 on 2026-01-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
