# Generated by Django 6.0.1 on 2026-01-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Краткое описание для поисковиков', verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если пусто — используется обычный заголовок', max_length=255, verbose_name='SEO Title'),
        ),
    ]
