# Generated by Django 6.0.1 on 2026-01-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeblock',
            options={'ordering': ['order'], 'verbose_name': 'Home Block', 'verbose_name_plural': 'Home Blocks'},
        ),
    ]
