# Generated by Django 6.0.1 on 2026-01-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
