# Generated by Django 6.0.1 on 2026-01-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AddField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/', verbose_name='Файл (ТЗ, документы)'),
        ),
    ]
