# Generated by Django 6.0.1 on 2026-01-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_adminnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
