# Generated by Django 6.0.1 on 2026-01-13 07:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'О нас'), ('cooperation', 'Сотрудничество'), ('faq', 'F.A.Q.')], max_length=20, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание вакансии')),
                ('requirements', tinymce.models.HTMLField(blank=True, verbose_name='Требования')),
                ('responsibilities', tinymce.models.HTMLField(blank=True, verbose_name='Обязанности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Вакансия активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
