# Generated by Django 6.0.1 on 2026-01-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_page_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title'),
        ),
    ]
