# Generated by Django 6.0.1 on 2026-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_page_seo_description_page_seo_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
